apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: depi
  ports:
    - port: 6000
      targetPort: 80
      name: http
    - port: 8090
      targetPort: 90
      name: xyz
